"""init

Revision ID: 18a877083f8c
Revises: 
Create Date: 2024-10-19 23:03:53.844286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a877083f8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('office_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_office_service_unique', 'office_services', ['office_id', 'service_id'], unique=True)
    op.create_table('office_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('window_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_office_window_unique', 'office_windows', ['office_id', 'window_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_office_window_unique', table_name='office_windows')
    op.drop_table('office_windows')
    op.drop_index('idx_office_service_unique', table_name='office_services')
    op.drop_table('office_services')
    op.drop_table('offices')
    # ### end Alembic commands ###
