"""enchance_office_model

Revision ID: 3f7dd3d6894c
Revises: 18a877083f8c
Create Date: 2024-10-20 03:37:20.282089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7dd3d6894c'
down_revision: Union[str, None] = '18a877083f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_office_users_unique', 'office_employees', ['office_id', 'user_id'], unique=True)
    op.add_column('offices', sa.Column('week_days', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('start_time', sa.String(), nullable=False))
    op.add_column('offices', sa.Column('end_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'end_time')
    op.drop_column('offices', 'start_time')
    op.drop_column('offices', 'week_days')
    op.drop_index('idx_office_users_unique', table_name='office_employees')
    op.drop_table('office_employees')
    # ### end Alembic commands ###
